### ISSUE TITLE
Setup: IDEs, package managers

### ISSUE THREAD

**Issue by vansteph** [ubvu/bytes-and-bites#3]
- What's the best coding / virtual environment
- VS code can take any language (Python or R), does have package environment, content environment, Brett recommends it for Go and C programming, good Python support,
- PyCharm for Python if we want to have it language specific

**Comment by paulmaxus** [comment]
- venv vs conda
- high-level stuff: what background color to use etc.

**Comment by paulmaxus** [comment]
this topic is a superset of #4 so we should include its contents here

**Comment by paulmaxus** [comment]
demo by 2-3 people, (briefly) presenting their everyday use of an IDE e.g. JupyterLab, RStudio, VSCode;
leaving room for discussion
